# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18xiG6WQ4z_7t2YwgPliUsuH9eA_cpaAs
"""

import streamlit as st
import pandas as pd
import pickle

# =========================
# PAGE CONFIG
# =========================
st.set_page_config(
    page_title="MovieVerse",
    page_icon="🎬",
    layout="wide",
)

# =========================
# CUSTOM CSS
# =========================
st.markdown("""
<style>
body {
    background-color: #0f172a;
}
.main {
    background-color: #0f172a;
}
h1, h2, h3, h4 {
    color: #f8fafc;
}
.card {
    background: #020617;
    padding: 20px;
    border-radius: 15px;
    box-shadow: 0px 10px 25px rgba(0,0,0,0.4);
    margin-bottom: 20px;
}
.badge {
    display: inline-block;
    background: linear-gradient(135deg, #6366f1, #8b5cf6);
    color: white;
    padding: 5px 12px;
    border-radius: 20px;
    font-size: 12px;
}
.footer {
    text-align: center;
    color: #94a3b8;
    margin-top: 50px;
}
</style>
""", unsafe_allow_html=True)

# =========================
# LOAD DATA
# =========================
@st.cache_data
def load_movies():
    with open("movies.pkl", "rb") as f:
        return pickle.load(f)

movies = load_movies()

# =========================
# HEADER
# =========================
st.markdown("""
<h1>🎬 MovieVerse</h1>
<p style="color:#94a3b8;">
Explore film data with a modern and interactive interface
</p>
""", unsafe_allow_html=True)

# =========================
# SIDEBAR
# =========================
with st.sidebar:
    st.header("🔍 Filter")
    search = st.text_input("Cari Judul Film")
    min_rating = st.slider("Minimal Rating", 0.0, 10.0, 5.0, 0.1)
    max_rows = st.selectbox("Jumlah Film", [10, 20, 50, 100], index=1)

# =========================
# FILTER LOGIC
# =========================
filtered = movies.copy()

if search:
    filtered = filtered[
        filtered["title"].str.contains(search, case=False, na=False)
    ]

if "vote_average" in filtered.columns:
    filtered = filtered[filtered["vote_average"] >= min_rating]

# =========================
# MOVIE GRID
# =========================
st.subheader("🎞️ Daftar Film")

cols = st.columns(3)
for idx, row in filtered.head(max_rows).iterrows():
    with cols[idx % 3]:
        st.markdown(f"""
        <div class="card">
            <h4>{row['title']}</h4>
            <span class="badge">⭐ {row.get('vote_average', 'N/A')}</span>
            <p style="color:#94a3b8; margin-top:10px;">
                {row.get('overview', 'Tidak ada deskripsi.')[:120]}...
            </p>
        </div>
        """, unsafe_allow_html=True)

# =========================
# DETAIL SECTION
# =========================
st.markdown("---")
st.subheader("🎥 Detail Film")

selected = st.selectbox(
    "Pilih Film",
    filtered["title"].values if not filtered.empty else []
)

if selected:
    data = filtered[filtered["title"] == selected].iloc[0]

    st.markdown(f"""
    <div class="card">
        <h2>{data['title']}</h2>
        <p><strong>⭐ Rating:</strong> {data.get('vote_average', '-')}</p>
        <p><strong>📅 Rilis:</strong> {data.get('release_date', '-')}</p>
        <hr style="border:0.5px solid #1e293b;">
        <p style="color:#e5e7eb;">{data.get('overview', 'Tidak ada sinopsis.')}</p>
    </div>
    """, unsafe_allow_html=True)

# =========================
# FOOTER
# =========================
st.markdown("""
<div class="footer">
🚀 MovieVerse App | Built with Streamlit
<br>Data Source: movies.pkl
</div>
""", unsafe_allow_html=True)